# Setup
title: Thoughts
tagline: ...of a curious soul
url: https://thoughts.curious.pm
paginate: 1
baseurl: ""
permalink: pretty
author: Ankit Aggarwal
email: a@curious.pm
github_username: curious-pm
linkedin_username: curious-pm

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Ankit Aggarwal
  url: https://linkedin.com/in/curious-pm
  email: a@curious.pm

# Custom vars
version: 3.0.0
